config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: %i[edit update]

  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :address, :city, :state, :postcode, :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update]
  def index
    @users = User.all.order(:created_at)
  end

  def edit
  end

  def update
    @user.assign_attributes(user_params)
    @changed = @user.changed?
    @user.save
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :address, :city, :state, :postcode, :phone)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/_modal.html.erb
<%= simple_form_for user, remote: true do |f| %>
  <div class="modal-header">
    <h5 class="modal-title">Edit User</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">

    <div class="row">
      <div class="col-md-6"><%= f.input :first_name %></div>
      <div class="col-md-6"><%= f.input :last_name %></div>
    </div>

    <%= f.input :address %>

    <div class="row">
      <div class="col-md-6"><%= f.input :city %></div>
      <div class="col-md-6"><%= f.input :state %></div>
      <div class="col-md-6"></div>
    </div>

    <div class="row">
      <div class="col-md-6"><%= f.input :postcode %></div>
      <div class="col-md-6"><%= f.input :phone %></div>
    </div>


  </div>
  <div class="modal-footer">
    <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr data-user-id='<%= user.id %>'>
  <th scope="row"><%= user.id %></th>
  <td><%= user.first_name %> <%= user.last_name %></td>
  <td><%= user.address %></td>
  <td><%= user.city %> / <%= user.state %></td>
  <td><%= user.postcode %></td>
  <td><%= user.phone %></td>
  <td><%= link_to edit_user_path(user), remote: true do %><i class="fas fa-edit"></i><% end %></td>
</tr>

app/views/users/edit.html.erb
<h1 class="my-3">Edit User</h1>

<%= simple_form_for @user do |f| %>
  <div class="row">
    <div class="col-md-6"><%= f.input :first_name %></div>
    <div class="col-md-6"><%= f.input :last_name %></div>
  </div>

  <%= f.input :address %>

  <div class="row">
    <div class="col-md-6"><%= f.input :city %></div>
    <div class="col-md-6"><%= f.input :state %></div>
    <div class="col-md-6"></div>
  </div>

  <div class="row">
    <div class="col-md-6"><%= f.input :postcode %></div>
    <div class="col-md-6"><%= f.input :phone %></div>
  </div>



  <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>
<% end%>

app/views/users/edit.js.erb
$('#userModal .modal-content').html('<%= j render "users/modal", user: @user %>');
$('#userModal').modal('show');

app/views/users/index.html.erb
<h1 class="my-3">Users List</h1>

<table class="table">
<thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">City / State</th>
      <th scope="col">Postcode</th>
      <th scope="col">Phone</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>

<div class="modal fade" id="userModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        INPUTS
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary btn-block">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/users/update.js.erb
<% if @user.errors.any? %>
  $('#userModal .modal-content').html('<%= j render "users/modal", user: @user %>');
<% else %>
  $('#userModal').modal('hide');

  $('tr[data-user-id="' + <%= @user.id %> + '"]').replaceWith('<%= j render "users/user", user: @user %>');

  <% if @changed %>
    $('tr[data-user-id="' + <%= @user.id %> + '"]').addClass('edited');
  <% end %>


<% end %>